title: Jesstern

theme: PaperMod
languageCode: en-us
baseURL: "https://jesstern.com/"

pagination:
  pageSize: 10

enableGitInfo: true

taxonomies:
  category: categories
  tag: tags

menu:
  main:
    - name: About
      url: about/
      weight: 9

params:
  author: "Jesstern Rays"
  defaultTheme: auto
  disableThemeToggle: false

  ShowToc: false
  TocOpen: false

  hideAuthor: true
  hideFooter: true

  ShowBreadCrumbs: false
  ShowReadingTime: false
  ShowPostNavLinks: false
  ShowCodeCopyButtons: false

  profileMode:
    enabled: true
    title: "Jesstern"
    subtitle: "Welcome to the digital home of Jesstern Rays"
    imageUrl: "https://avatars.githubusercontent.com/u/1199611?v=4"
    imageWidth: 150
    imageHeight: 150
    imageTitle: "Jesstern"

  homeInfoParams:
    Title: "Hello, I'm Jesstern! ðŸ‘‹"
    Content: "Welcome to my personal digital space."

  socialIcons:
    - name: "LinkedIn"
      url: "http://jsrn.me/in"
    - name: "GitHub"
      url: "http://jsrn.me/gh"
    - name: "Email"
      url: "/contact"

  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/favicon/safari-pinned-tab.svg"

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
